### ISSUE TITLE
render BAM read pairs / multi-segment reads

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#207] opened 2013-02-14 15:33 UTC
Currently, mutli-segment BAM reads are not displayed as connected to their mate.  Need to lay them out as a single multi-segment feature, connected with a little dashed line or something.

**Comment by cmdcolin** [comment] 2018-07-20 18:22
The idea of rendering read pairs together is now I think a duplicate of #521

The idea of the concepts in the email written by @aswarren were started to be addressed in a PR created by him in #433 and then finished by #485. The "Use reverse template" option (useReverseTemplate: true in config) which does this has existed since about 1.11 versions of jbrowse.

Hope that helps


This screenshot from #485 shows how the RNA-seq reads are essentially colored according to the strand direction of the genes themselves even though there are plus and minus paired end reads in the actual data

![](https://camo.githubusercontent.com/d317d83f9bd77aefde605a81c37602ba4ef90d9d/687474703a2f2f6b6f6b652e617372632e6b616e617a6177612d752e61632e6a702f484f57544f2f6a62726f7773652d62616d2d70652d737472616e6465642d636f6c6f722e706e67)

**Closed by cmdcolin** 2018-07-20 18:22 UTC
Labels: feature req
