### ISSUE TITLE
Parsing gVCF and symbolic alleles

### ISSUE THREAD

**Issue by nathanhaigh** [GMOD/jbrowse#902] opened 2017-06-20 15:03 UTC
The VCF v4.3 spec details in section 5.5 the use of a "symbolic allele" `<*>` in `gVCF` files. Currently, JBrowse doesn't seem to correctly deal with VCF files containing these:

![image](https://user-images.githubusercontent.com/2037575/27340246-297354de-5619-11e7-852c-cee8fb9644ef.png)

**Comment by cmdcolin** [comment] 2017-06-23 15:32
I think some of these issues are fixed by this pull request https://github.com/GMOD/jbrowse/pull/847


For example, the gVCF style depends on the "END" info field too which I think is aided by this

**Comment by cmdcolin** [comment] 2018-04-02 23:21
This should be fixed since 1.13.1

Feel free to check out and open new issue if there is still unexpected behavior

**Closed by cmdcolin** 2018-04-02 23:21 UTC
Labels: feature req, high priority, needs review
