### ISSUE TITLE
calculate MD in BAM data if it is missing

### ISSUE THREAD

**Issue by thon-deboer** [GMOD/jbrowse#1022] opened 2018-03-12 21:41 UTC
I have a BAM file that has mismatches in the BAM file, but the CIGAR string does not show any mismatches (100M etc).

IGV seems to be able to display those mismatches, but it seems IGV does not...

Is there another BAM parser that perhaps allows that?
I have no control over the BAM files so cannot update the CIGAR strings..

JBROWSE
![image](https://user-images.githubusercontent.com/22755975/37311051-31101460-2603-11e8-84f6-8ca6da33696d.png)

IGV
![image](https://user-images.githubusercontent.com/22755975/37311107-5794312a-2603-11e8-9a7a-217dbc1842b8.png)

**Comment by thon-deboer** [comment] 2018-03-12 21:43
OK..I think i know what is going on...There is no MD tag in the read and it seems jbrowse needs that (IGV does not then?)...Not sure if it is easy to add the MD tag, but guess that is the reason?

**Comment by cmdcolin** [comment] 2018-03-12 23:28
This is an old feature request to auto calculate MD tag https://github.com/GMOD/jbrowse/issues?page=5&q=is%3Aissue+is%3Aopen

Could be useful to provide error if MD tag does not exist?

I think samtools calmd command can populate this field though

**Comment by rbuels** [comment] 2018-03-12 23:51
So is this a duplicate of #179 then?

**Comment by thon-deboer** [comment] 2018-03-13 00:18
Guess it is a feature request indeed...#179 seems indeed a duplicate of this...Feel free to close either, although this one has more background...Surprising noone has run into this since 2012

**Comment by keiranmraine** [comment] 2018-03-13 09:23
@thon-deboer ideally you want to have MD in your BAMs as it's the fastest way to render (even in IGV) but it does have a small file-size overhead.  You may also find some analysis algorithms would give unexpected results without the MD tag.  Samtools has a `calmd` option.

FYI if/when JBrowse supports CRAM it will need to be able to construct the MD as a common compression option is to drop all fields that can be calculated on reading.

**Comment by thon-deboer** [comment] 2018-03-13 09:39
@keiranmraine Yes, I understand that MD tags would be better, but I am developing a tool for a customer that used the BAM files for other apps and they just don't want to mess with the BAM files, but I will see if I can convince them...I have no control over the BAM files.

**Comment by colindaven** [comment] 2018-03-13 16:00
Have been using MD tags in BAMs for many years with JBrowse. Makes sense to add calmd to your pipeline in many cases (if you can). If you have a lot of data or want to provide web-based infrastructure there are big drawbacks to IGV, though some do really love it.

**Comment by keiranmraine** [comment] 2018-03-13 19:36
@thon-deboer , I hesitate to say this but GBrowse used to fall back (and likely still does) to generating the mismatch data itself if it failed to find an MD tag (it was initially the default).  IF they really don't want to change the BAMs it's an option...

**Comment by thon-deboer** [comment] 2018-03-13 21:16
well..wouldn't you know...I nagged the customer enough for them to consider adding the MD tag..>Problem solved!

**Comment by rbuels** [comment] 2018-03-14 01:02
ooo we need to steal the GBrowse MD calculation code.  @keiranmraine do you know what perl module that's in?

**Comment by rbuels** [comment] 2018-03-14 01:32
Hmm, well I'm going to close #179 and just change this one's title to be concise

**Comment by keiranmraine** [comment] 2018-03-14 09:04
@rbuels, do you want to recreate the MD or use a different path to get the match/mismatch/ins/del info?

There are 2 functions in the Bio::DB::Sam legacy module that reference MD (superseded by Bio::DB::HTS), but they don't construct the MD.  One creates the padded-alignment (as in the JBrowse popup, not taking into account mismatch) the other falls back to the C binding.  Both in [this block][bio-db-sam-md]

If you do want to generate the MD (and NM) you can follow [this logic][cgp-pindel-calmd] from our pindel code base.

[bio-db-sam-md]: https://github.com/GMOD/GBrowse-Adaptors/blob/4ad3fabcad508811b031258e8458ed06978356c3/Bio-SamTools/lib/Bio/DB/Bam/AlignWrapper.pm#L219-L311
[cgp-pindel-calmd]: https://github.com/cancerit/cgpPindel/blob/f0bb174e0dd6109d38c32f10e741e90de391b689/perl/lib/Sanger/CGP/Pindel/OutputGen/PindelRecordParser.pm#L594-L707

**Comment by rbuels** [comment] 2018-07-18 20:35
implementation sketch:
* add a checkbox in the track menu for "calculate mismatches (MD)", default off
* this would recreate the BAM store with a "calculateMD" option set on
* each LazyFeature would lazily calculate the MD on demand

**Comment by cmdcolin** [comment] 2020-07-06 21:21
The automatic MD calculation feature has been added to our new jbrowse 2 repository :balloon: :tada: 

Unless there is strong need this feature might not be backported to jbrowse 1, so keep your eyes out for jbrowse 2

https://github.com/GMOD/jbrowse-components/pull/1042

**Comment by cmdcolin** [comment] 2020-09-03 00:27
Went ahead and backported this to dev branch of this repo now just for completeness sake. Feel free to test, pending release

**Closed** 2020-09-03 00:29 UTC
Labels: feature req
