### ISSUE TITLE
FASTA save button missing in Safari

### ISSUE THREAD

**Issue by kkarra** [GMOD/jbrowse#714] opened 2016-03-16 22:06 UTC
When you click on a CanvasFeature the pop-up box displays the sequence and a save button in other browsers. But, in Safari Version 9.0 (11601.1.56)  - the button is missing.

**Comment by enuggetry** [comment] 2016-03-16 23:13
I can reproduce this.  Thanks for bring it up.

This button does not show up in Safari:
![ice_screenshot_20160316-160746](https://cloud.githubusercontent.com/assets/10053377/13831554/caba075a-eb91-11e5-88ad-e9fb8c0a4802.png)

**Comment by cmdcolin** [comment] 2016-03-21 18:21
Probably related to this https://github.com/GMOD/jbrowse/issues/412

I forget the exact issues with this but it might be able to be re-fixed on safari

**Comment by cmdcolin** [comment] 2016-06-20 16:08
The FileSaver.js demo that jbrowse uses sort of demonstrates the type of issues that are seen with safari https://eligrey.com/demos/FileSaver.js/

Instead of saving the file, it creates a new tab with the content, and then the user has to save the contents to a file themselves.

**Comment by rbuels** [comment] 2018-01-30 17:30
Well, back 3.5 years ago when we made this feature, it couldn't be made to work on Safari, because Safari didn't support creating files on the client side. But that may have changed with newer versions of Safari in the years since.

@cmdcolin you're on mac right?  do you have time to look into 1.) why the button is actually missing (it's supposed to be grayed out/disabled), 2.) whether the download functionality can be made to work in recent versions of safari, so we could maybe enable it for new Safaris. Assigning it to you for now, if you don't have time, just un-assign it.

**Comment by rbuels** [comment] 2018-02-20 19:30
i just confirmed that `save-generated-files` works on Safari 11.  Anybody have safari 10 or 9 to test?

**Comment by rbuels** [comment] 2018-02-20 19:38
I'm trying now to get a free Browserstack account for us to poke at this manually.

**Comment by rbuels** [comment] 2018-02-20 20:56
Got a browerstack account, tested that Safari 10 and 11 both support the generated file download, but Safari 9 and below do not.

**Closed by rbuels** 2018-02-20 20:56 UTC
Labels: bug, help wanted, needs review
