### ISSUE TITLE
Tabix indexed features' view details pop-up window doesn't render subFeatures correctly 

### ISSUE THREAD

**Issue by Yating-L** [GMOD/jbrowse#1072] opened 2018-06-21 19:38 UTC
I found two problems with the "view details" window of the Tabix indexed features

1) When a gene model has multiple subfeatures like CDSs and these CDSs use the same ID. The "view details" window will repeatedly render the CDSs 

2) We can click on a feature to view details and also right click on a feature and select "view details" from the drop-down menu. These two methods show different results. The former method usually only show partial subfeatures

**Comment by cmdcolin** [comment] 2018-06-23 03:59
Are you using the latest jbrowse? The issues from number 2 may be fixed in recent versions.

As for number 1, what is meant by this?

**Comment by Yating-L** [comment] 2018-06-25 15:23
@cmdcolin I am using JBrowse 1.14.1. It has those two issues.

For number 1, the example output GFF3 file of the Augustus gene prediction tool is like

<img width="833" alt="screen shot 2018-06-21 at 2 06 29 pm" src="https://user-images.githubusercontent.com/8609589/41859003-ca5a6396-7860-11e8-9134-4564bd830709.png">

Here you can see that for gene scaffold_16.g25 has 10 CDSs but all CDSs have the same ID. In this situation, when I click on "view details", the details window will list more than 10 CDSs. It will list CDS #1 to #10 and then repeat listing #1 to #10 then #1 to #10 or #1 to #8 or else.

**Comment by rbuels** [comment] 2018-06-25 22:18
Hmm it sounds like the default feature dialogue is not dealing well with a GFF3 feature that has multiple locations, as this CDS does. Either that, or the TabixIndexedGFF3 store might need to transform the GFF3 feature to JBrowse features a bit differently.

**Comment by cmdcolin** [comment] 2018-07-26 17:12
I'm unable to reproduce this bug currently. I wasn't sure if maybe something that is particular about this data set that @Yating-L posted but I made a dataset with this gff snippet and I can't reproduce still, attachment below:

[augustus.tar.gz](https://github.com/GMOD/jbrowse/files/2232914/augustus.tar.gz)

The resulting view details always has 10 CDS and it always seems to be a valid sequence.

@Yating-L any ideas? I'm trying right click and single click of the feature and it seems the same. I know some subfeature fetching was a problem in older versions of JBrowse pre-1.14.0 but @rbuels made a lot of fixes for GFF3Tabix in version 1.14.0 and so I'm not seeing it now

Note: The volvox data also has CDS with no ID so we do see this and test this in our sample data

**Comment by Yating-L** [comment] 2018-07-27 21:53
I tried the latest JBrowse-1.15.0 and still got the same problem. I attached the JBrowse Archive with Augustus track [here](https://wustl.box.com/v/tabix-augustus-track). Go to contig16:15164..44480. You will see a feature named contig16.g25.t1. The details window will list more than 10 CDSs

**Comment by cmdcolin** [comment] 2018-07-27 23:37
I am getting 10 CDS consistently no matter if I do Right click->View details or Single click on feature when viewing this with Chrome and Firefox and Edge on JBrowse 1.15.0 with this feature

There is 1 start codon feature and 10 CDS each time

I am very curious if I can get the issue reproduced, but I'm outta ideas :) Only thing I would suggest is maybe clear cache in case an old version of jbrowse code is being loaded somehow? Seems unlikely but ya

**Comment by Yating-L** [comment] 2018-07-30 14:18
@cmdcolin Did you try the track that I attached previously?[track](
https://wustl.box.com/v/tabix-augustus-track). Yours [augustus.tar.gz](url
https://github.com/GMOD/jbrowse/files/2232914/augustus.tar.gz) look very different from mine. How did you generate the track? Do you use the script 'flatfile-to-json.pl'? I used 'tabix' from samtools to index the track, refer to step1 - step3 in this [tutorial](https://github.com/Arabidopsis-Information-Portal/jbrowse-tabix-howto/wiki/Steps-to-process-GFF3-files).

**Comment by cmdcolin** [comment] 2018-07-30 14:45
You're right, my augustus.tar.gz had a flatfile-to-json.pl track, but remade it with tabix and also tried your archive and it seemed to be behaving fine as far as I could tell still!

**Comment by Yating-L** [comment] 2018-07-30 14:48
That's wired. I will try again. @cmdcolin what is your JBrowse version? 1.15.0?

**Comment by cmdcolin** [comment] 2018-07-30 14:52
Yep :)

**Comment by Yating-L** [comment] 2018-07-30 19:57
@cmdcolin I think 1.15.0 work and fixed the issue. But 1.12.5 is the latest version that compatible with Apollo (correct me if I am wrong). So we're stuck with 1.12.5? Any suggestions? Would Apollo support the latest JBrowse eventually?

**Comment by cmdcolin** [comment] 2018-07-30 22:10
I imagine it will be updated soon! It would be pretty complex to backport the newer fixes to the older version since it incorporates Node.js gff-js module and a new "redispatch" scheme so really upgrading to 1.15 is the best scenario

**Comment by cmdcolin** [comment] 2018-07-30 22:11
If its ok I will close this issue for now but feel free to post back if you find any issue

**Closed by cmdcolin** 2018-07-30 22:11 UTC
Labels: bug, needs review, waiting for user
