### ISSUE TITLE
VCF with no samples showing

### ISSUE THREAD

**Issue by shenweima** [GMOD/jbrowse#1427] opened 2019-09-25 01:17 UTC
I have a vcf file with more than 44,000 samples. I put this vcf ile into JBrowse, but it only show some basic information not including sample genotype.
This is my vcf file."http://202.194.139.32/jbrowse-1.12.3-release/Chinese_Spring/tracks/vcf/GBS_NG_GWAS_eff.vcf.gz"
![image](https://user-images.githubusercontent.com/8536868/65561430-0041f100-df75-11e9-9f64-f949dcbd4e3a.png)

![image](https://user-images.githubusercontent.com/8536868/65561496-3ed7ab80-df75-11e9-85e9-0a3ee57855a1.png)

**Comment by garrettjstevens** [comment] 2019-09-25 14:24
Hi there. I'm not actually able to reproduce this, I am able to see the sample info for this VCF (see sample screenshot below), at least for the small piece of it I downloaded to test with. When you click on a variant, there is a delay between the basic variant info appearing and the sample info appearing at the bottom of that window. If you click on a variant and leave the popup window open for a few minutes, does the sample info ever appear?

If that doesn't work, can you check for any error messages in your browser's developer tools console? Also, if you have a JBrowse instance with that track we could look at it might help.

Thanks.

![image](https://user-images.githubusercontent.com/25592344/65609228-6d598480-df7d-11e9-892e-eea779550a53.png)

**Comment by garrettjstevens** [comment] 2019-09-25 14:26
also the version of JBrowse you're using might be relevant, too.

**Comment by garrettjstevens** [comment] 2019-09-25 16:48
Actually, looking more closely at the URL you provided I found the JBrowse instance and the version. This was actually a bug in JBrowse that occurred when the VCF header was very large (which yours is, since it has so many samples). It was [fixed in v1.15.4](http://jbrowse.org/blog/2018/10/05/jbrowse-1-15-4.html), but it looks like you're using v1.12.3. If you upgrade to v1.15.4 or higher (the current version is v1.16.6) you will be able to see the sample information for the variants.

**Comment by cmdcolin** [comment] 2019-10-03 21:25
It looks like the fix is to use a newer version of jbrowse @shenweima 

Let me know if you need assistance in upgrading

**Closed by cmdcolin** 2019-10-03 21:25 UTC
