### ISSUE TITLE
CanvasFeatures assigned multiple onClick events on page load via setLocation and showTracks

### ISSUE THREAD

**Issue by aswarren** [GMOD/jbrowse#830] opened 2016-11-14 21:50 UTC
As far as I can tell this is a problem with CanvasFeatures.
HTMLFeatures implements a check, _featureIsRendered which CanvasFeatures does not.The result is that when fillFeatures ends up getting called by setLocation and showTracks there are multiple click events set on the same feature.

[fillFeatures](https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/CanvasFeatures.js#L246)

**Comment by cmdcolin** [comment] 2017-04-28 18:53
duplicate of https://github.com/GMOD/jbrowse/issues/498

will copy paste there!

**Closed** 2017-04-28 18:54 UTC
