### ISSUE TITLE
defaultTracks fail to show if there is a space in the label

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse#585] opened 2015-04-28 17:49 UTC
When setting defaultTracks in jbrowse.conf, if there is a space in the track label, the track will fail to display, while the rest of JBrowse works just fine with spaces in the labels.  I tried several variations on the defaultTracks syntax, including:
```
defaultTracks = Classical alleles,Polymorphisms,Curated Genes
defaultTracks = Classical%20alleles,Polymorphisms,Curated%20Genes
defaultTracks = "Classical alleles",Polymorphisms,"Curated Genes"
defaultTracks = 'Classical alleles',Polymorphisms,'Curated Genes'
defaultTracks = Classical%20alleles%2CPolymorphisms%2CCurated%20Genes
defaultTracks = Classical%20alleles+Polymorphisms+Curated%20Genes
```
None of which worked.  Of course, there is no mention in the documentation that spaces are not allowed (it specifies "machine readable", but since the rest of JBrowse works, I assume my track labels are machine readable).

**Comment by scottcain** [comment] 2015-04-28 17:50
If spaces are problematic, I think supporting URI escaping would be a reasonable alternative.

**Comment by cmdcolin** [comment] 2015-04-29 22:11
First of all, the "defaultTracks" parameter is very sensitive to several things: the pre-existing cookies and the URL. If there are is a &tracks= section specified on the URL, then it ignores defaultTracks. If there is an previous set of tracks that were viewed in the cookies, then it ignores the defaultTracks parameter. The defaultTracks is really only for a "first time" visitor to your browser.

Second of all, no quotes or URL escaping should be used in the .conf format. The .conf format is a very custom file format and very simple.

Third, if you wanted this track to just always load, use browser.config.alwaysOnTracks. WebApollo uses this for example for it's custom User-created annotations track. It just so happens that this parameter was undocumented before now :)

Essentially I don't think the problem is due to spaces

**Comment by scottcain** [comment] 2015-04-30 21:37
Hi @cmdcolin ,

Actually, I'm pretty sure defaultTracks is exactly what I want.  I created an Ubuntu virtual machine that I just cloned over and over to make sure every time I went to the site it was a "first time" visit so that I could test the various options.  I just want the tracks turned on the first time someone visits the site and then let the user decide what to have after that.  forceTracks might be a viable alternative, I'll test to see if it works.  I kind of like the idea of letting it be overridden by a URL list, so that might be better (though the naming is not so great: force to me says those tracks are always there, darn it! Where as default means they're there unless you have a better idea, like a cookie or a list from a URL--so it goes).

I am pretty sure that spaces are the problem, because during my testing, the only thing that worked was to add underscores where there were spaces in both the defaultTracks setting and in the track config.  Taking the underscores back out broke it again, which is to say in the above example, I would only get the "Polymorphisms" track, but not the "Classical alleles" or "Curated genes" tracks.

Now, is this a huge problem for me? No, because I can just add the underscores and be done, but since it wasn't documented to be required, it's technically a bug.

**Comment by cmdcolin** [comment] 2015-04-30 21:54
I guess I can see where this could be confusing, but i am pretty sure the spaces aren't the problem, at least in my (brief) test cases. Nevertheless, it is more common to use the label parameter with underscores, and to use the "key" parameter as the display names with spaces and things, because recall that the "label" is really more of an internal ID and the key is the display name.

Anyways, to be clear, to test the defaultTracks function, you have to really set yourself up as a "new user" i.e.

1. Clear cache and cookies
2. Visit the URL of your browser without any ?tracks= section in it

In my tests, this properly opens up the list of default tracks

**Comment by cmdcolin** [comment] 2015-04-30 22:02
And the list of default tracks that i have is pretty wonky, e.g.

    defaultTracks=Testing spaces,volvox_microarray_bw_density,Testing spaces blah,Testing spaces 2

**Comment by selewis** [comment] 2015-05-06 21:10
Must say that these particular tags are very non-intuitive, even for
something that is internal configuration. "Label" is not what the user
sees? That's just weird. And "key" is so generic a tag that it's virtually
meaningless.

Yes, very confusing, an unfortunate choice.

-S

**Comment by cmdcolin** [comment] 2015-05-06 21:34
label is what the user sees if no key is specified, but key overrides it with a better description. and label is the "required" parameter for the command line scripts, and it is used in directory path names, so if you don't like spaces in your directory paths, then best not to have spaces in the label.

**Comment by cmdcolin** [comment] 2015-05-07 00:35
In any case, i'm probably going to close this unless there is any case that can be made that it is actually a bug

**Closed by cmdcolin** 2015-05-07 00:35 UTC
